# Generated by Django 2.0.7 on 2018-07-09 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ciclo', models.CharField(choices=[('PRIMERO', 'primero'), ('SEGUNDO', 'segundo'), ('TERCERO', 'tercero'), ('CUARTO', 'cuarto'), ('QUINTO', 'quinto'), ('SEXTO', 'sexto'), ('SEPTIMO', 'septimo'), ('OCTAVO', 'octavo'), ('NOVENO', 'noveno'), ('DECIMO', 'decimo')], default='PRIMERO', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Titulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validador.Titulacion'),
        ),
    ]
